language: php
php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION="4.2.*" DB=mysql

jobs:
  include:
    - stage: build
      script:
        - composer install
        - cp .env.test .env
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:schema:create --env=test
        - php bin/console doctrine:fixtures:load -n --env=test
    - stage: test
      script: php bin/phpunit
    - stage: deploy
      deploy:
        provider: heroku
        api_key: $HEROKU_KEY
        app: $HEROKU_APP
    - stage: notify
      notifications:
        email: quenting92@gmail.com

on:
  branch: master