language: php

sudo: true

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION="4.2.*" DB=mysql

install:
  - composer self-update
  - cp .env.test .env
  - composer install

jobs:
  include:
    - stage: test
      script: php bin/phpunit
    #- stage: build
    #  script:
    #   - php bin/console cache:clear
    #   - php bin/console doctrine:database:create
    #   - php bin/console doctrine:schema:create
    #   - php bin/console doctrine:fixtures:load -n
    - stage: deploy-preprod
      deploy:
        provider: heroku
        api_key: $HEROKU_KEY
        app: $HEROKU_PP_APP
    - stage: deploy
      deploy:
        provider: heroku
        api_key: $HEROKU_KEY
        app: $HEROKU_APP
on:
  branch: master

notifications:
  email: [quenting92@gmail.com]
