language: php
# Versions of PHP you want your project run with.
php:
  - 7.2
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart

sudo: false

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: hhvm
  allow_failures:
    - php: hhvm

env:
  - SYMFONY_VERSION="4.2.*" DB=mysql

before-install:
  - composer self-update

install:
  - cp .env.test .env
  - composer install
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create --force
  - php bin/console doctrine:fixtures:load

script:
  - phpunit

notifications:
  email: [quenting92@gmail.com]
