language: php

sudo: true

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

# Define an environment variable
env:
  - SYMFONY_VERSION="4.2.*" DB=mysql

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer self-update
  - cp .env.test .env
  - composer install

jobs:
  include:
    - stage: test
      script: php bin/phpunit
    - stage: deploy
      deploy:
        provider: heroku
        api_key: $HEROKU_KEY
        app: $HEROKU_APP
on:
  branch: master
# Run script

# After a build, send email notification with the build results
notifications:
  email: [quenting92@gmail.com]
